# @package _global_

# sweep_test.yaml
datamodule:
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ["2018-06-01", "2018-07-01"]}
    val: 
      time: {_target_: builtins.slice, _args_: ["2018-06-01", "2018-07-01"]}
    test:
      time: {_target_: builtins.slice, _args_: ["2018-06-01", "2018-07-01"]}
