# @package _global_

# sweep_test.yaml
datamodule:
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ["2014-12-20", "2020-02-01"]}
    val: 
      time: {_target_: builtins.slice, _args_: ["2014-12-20", "2020-02-01"]}
    test:
      time: {_target_: builtins.slice, _args_: ["2014-12-20", "2020-02-01"]}
